# SPDX-FileCopyrightText: Copyright (c) 2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
AllCops:
  Exclude:
    - 'bin/**/*'
    - 'assets/**/*'
    - 'vendor/**/**'
  DisplayCopNames: true
  TargetRubyVersion: 3.2
  SuggestExtensions: false
  NewCops: enable
plugins:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rake
Minitest/EmptyLineBeforeAssertionMethods:
  Enabled: false
Gemspec/RequiredRubyVersion:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
