# SPDX-FileCopyrightText: Copyright (c) 2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
extends: default
rules:
  line-length: disable
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 2
  truthy:
    level: warning
    allowed-values: [ 'on', 'true', 'false', 'yes', 'no' ]
